name: M1LTE
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.12
  - gensim
  - jupyterlab=4.1.0
  - jupyterlab-latex=3.1
  - matplotlib=3.8.2
  - nltk
  - numpy=1.26.4
  - pandas
  - python=3.11
  - spacy=3.7