[project]
name = "M1LTE"
version = "0.1.0"
description = "Resources for M1LTE at UPC"
authors = ["Alexandre Roulois <alexandre.roulois@u-paris.fr>"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/Alex-bzh/python-M1LTE"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[dependencies]
beautifulsoup4 = ">=4.12.0"
matplotlib = "~=3.0"
numpy = ">1.25"
pandas = ">2.0"
python = ">3.10"
seaborn = ">0.13.0"
